# TODO: add randomized and perhaps more from nick/james project (e.g., world bank region)
# could include prospective reg, study type

# Create table of trial characteristics for included trials using priority ictrp registration

# Prepare cross-registrations ---------------------------------------------

trials_all_registries <-
  registrations |>

  # Get all trns for included trials
  semi_join(trials, by = "id") |>


  # Limit to distinct registries per trial
  # NOTE: some trials, e.g. tri00985, have >1 registration but in single registry, so count for registry and not cross-registration
  distinct(id, registry) |>
  arrange(registry)

# Create boolean for cross-registrations
cross_registrations <-
  trials_all_registries |>
  group_by(id) |>
  summarize(crossreg = if_else(n() > 1, TRUE, FALSE))

# Prepare pandemic "semester" ---------------------------------------------
pandemic_semester <-
  trials |>
  mutate(
    month_completion =
      lubridate::floor_date(date_completion, "month"),

    semester = case_when(
      month_completion < as.Date("2020-07-01") ~ 1,
      month_completion < as.Date("2021-01-01") ~ 2,
      month_completion < as.Date("2021-07-01") ~ 3,
    ),

    semester_fct = ordered(semester,
                           labels = c("Jan 2020-Jun 2020", "July 2020-Dec 2020", "Jan 2021-Jun 2021")
    )
  ) |>
  select(id, ends_with("completion"), starts_with("semester"))


# Prepare randomization ---------------------------------------------------

# Randomization inferred from design and titles in ictrp

# Load study design extractor function
source(here::here("docs", "analysis", "extract_design.R"))

ictrp_design <-

  # Prepare ictrp for included trials
  ictrp |>

  semi_join(trials, by = c("trn" = "trn_ictrp_priority")) |>
  left_join(select(trials, id, trn_ictrp_priority), by = c("trn" = "trn_ictrp_priority")) |>
  select(trn, registry, public_title) |>

  # Add study design
  left_join(readr::read_csv(ictrp_design_path), by = "trn") |>

  # Remove duplicates (euctr)
  # Note: EUCTR2020-001264-28 has different study design but just spacing
  distinct() |>
  distinct(trn, .keep_all = TRUE) |>
  assertr::assert(assertr::is_uniq, trn) |>

  # Fill in missing study designs
  # NOTE: ND checked and these are due to his cleaning, and ok
  rows_patch(tribble(
    ~trn, ~study_design,
    "NCT04667780", "Allocation: Randomized. Intervention model: Parallel Assignment. Primary purpose: Treatment. Masking: None (Open Label).",
    "NCT04926428", "Allocation: N/A. Intervention model: Single Group Assignment. Primary purpose: Diagnostic. Masking: None (Open Label).",
    "NCT04933864", "Allocation: Randomized. Intervention model: Parallel Assignment. Primary purpose: Treatment. Masking: Single (Outcomes Assessor).",
  ), by = "trn") |>
  assertr::assert(assertr::not_na, study_design) |>

  # Extract design
  extract_design() |>

  # Fill in missing randomization
  # NOTE: Dual coded MSH/ND
  rows_patch(tribble(
    ~trn, ~randomisation,
    "ChiCTR2000029487", "Yes",  # "Third party uses random number table for random grouping"
    "ChiCTR2000030116", "Yes",  # "Generated by a table of random numbers"
    "ChiCTR2000030810", "Yes",  # "Digital random method"
    "ChiCTR2000030773", "No",  #
    "ChiCTR2000030704", "Yes",  # "doctor decides that by envelope method"
    "ChiCTR2000040632", "No",  # "No Randomization was done. It was a single group study"
    "CTRI/2020/10/028486", "Yes",  # "we will randomize the patients into two groups"
    "CTRI/2020/10/028485", "No",  # Method of Generating Random Sequence: Not applicable
    "ISRCTN95933274", "Yes",  # "Randomised controlled trial"
    "ISRCTN34160010", "No",  # "Non randomised study"
    "TCTR20210125002", "No",  # "Single arm"
  ), by = "trn") |>
  assertr::assert(assertr::not_na, randomisation) |>

  # Change to boolean
  mutate(is_randomized = if_else(randomisation == "Yes", TRUE, FALSE))


# Prepare ICTRP -----------------------------------------------------------

# Get ictrp data for priority trns
trial_characteristics <-
  ictrp |>

  semi_join(trials, by = c("trn" = "trn_ictrp_priority")) |>
  left_join(select(trials, id, trn_ictrp_priority), by = c("trn" = "trn_ictrp_priority")) |>
  relocate(id, .before = 1) |>

  # Some EUCTR trials (n = 3) duplicated in ictrp, so select earliest registered (since EUCTR no last updated date)
  group_by(trn) |>
  arrange(date_registration, .by_group = TRUE) |>
  slice_head(n = 1) |>
  ungroup() |>

  mutate(

    # Tidy phases
    phase = if_else(phase == "Phase 1-2", "Phase 1/Phase 2", phase),

    # Tidy enrollment
    target_enrollment = na_if(target_enrollment, "Not Available"),
    target_enrollment = as.numeric(target_enrollment),

    # Add results flag
    has_result = if_else(id %in% unique(results$id), "With Results", "Without Results"),

    # Add multinational flag
    multinational = if_else(stringr::str_detect(countries, ","), TRUE, FALSE)
  ) |>

  # Add registries
  left_join(cross_registrations, by = "id") |>

  # Add pandemic semester
  left_join(pandemic_semester, by = "id") |>

  # Add randomization
  left_join(select(ictrp_design, trn, is_randomized), by = "trn") |>
  assertr::assert(assertr::not_na, is_randomized)


# Prepare top interventions -----------------------------------------------

# Get trials with row per unique intervention
# NOTE: There are trials in multiple rows but not same intervention in multiple rows (even if used in multiple arms)
trials_interventions <-

  # Get arms of included trials
  arms |>
  semi_join(trials, by = "id") |>

  # Limit to experimental
  filter(type == "experimental") |>

  # Get row per intervention (i.e., trials may be in multiple rows)
  tidyr::separate_rows(intervention, sep = ";") |>

  # Limit to 1 row per intervention in a trial (since some interventions in more that one arm)
  distinct(id, intervention, .keep_all = TRUE)

# How many trials per intervention?
intervention_counts <-
  trials_interventions |>
  count(intervention, name = "n_trials") |>
  arrange(desc(n_trials))

# How many trials investigating how many interventions?
trials_intervention_counts <-
  intervention_counts |>
  count(n_trials, name = "n_intervention")

N_TOP_INTERVENTIONS <- 5

# Top interventions
# NOTE: "traditional medicine" collapses many interventions and hence not a true intervention
top_interventions <-
  intervention_counts |>
  filter(intervention != "Traditional Medicine") |>
  slice_head(n = N_TOP_INTERVENTIONS)

# Get trials with common interventions (with 1 row per common intervention)
trials_common_interventions <-

  trials_interventions |>

  # Limit to common interventions
  filter(intervention %in% top_interventions$intervention)

# Prepare interventions characteristics table
tbl_interventions_top <-
  trials_common_interventions |>

  # Add results flag
  mutate(
    has_result = if_else(id %in% unique(results$id), "With Results", "Without Results")
  ) |>

  select(has_result, intervention) |>

  gtsummary::tbl_summary(
    by = has_result,
    label = list(intervention ~ glue::glue("Top {N_TOP_INTERVENTIONS} Interventions")),
    sort = all_categorical() ~ "frequency"
  ) |>
  add_overall()|>
  bold_labels()

# Prepare table 1 ---------------------------------------------------------

# library(forcats)
# library(gtsummary)

tbl_trials <-
  trial_characteristics |>

  select(has_result,target_enrollment, crossreg, multinational, is_randomized, phase, semester_fct
         #,study_type,recruitment_status, retrospective_registration, date_registration #or date_completion used in main analysis? or pandemic "semester"?
  ) |>

  # Recode booleans to categorical
  # NOTE: Could instead have single line for "cross-registered" and "multinational"
  # mutate(
  #   crossreg = if_else(crossreg, "Multi", "Single"),
  #   multinational = if_else(multinational, "Multi", "Single")
  # ) |>

  gtsummary::tbl_summary(
    by = has_result,
    # type = all_continuous() ~ "continuous2",
    # statistic = all_continuous() ~ c("{N_nonmiss}",
    #                                  "{median} ({p25}, {p75})",
    #                                  "{min}, {max}"),
    missing = "no",
    label = list(
      target_enrollment ~ "Target enrollment",
      # study_type ~ "Study type",
      crossreg ~ "Cross-registered",
      multinational ~ "Multinational",
      is_randomized ~ "Randomized",
      phase ~ "Trial Phase",
      semester_fct ~ "Pandemic phase"
    ),
    # value = list(crossreg ~ c("TRUE", "FALSE")),
    # sort = list(
    # cross_registry ~ "frequency",
    # countries ~ "frequency"
    # ),
  )|>

  add_overall()|>

  # add_difference(include = target_enrollment)|>

  # modify_header(label = "**Publication Type**")|>

  bold_labels() #|>
  #modify_spanning_header(all_stat_cols() ~ "**Results Disseminated**") |>
  # modify_caption("**Trial Characteristics** (N = {N})")



# Combine characteristics table -------------------------------------------

tbl_characteristics <-
  tbl_stack(list(tbl_trials, tbl_interventions_top))

# gt_tbl_trials <- as_gt(tbl_characteristics)
# gt::gtsave(gt_tbl_trials, here::here("docs", "figures", "tbl-trials.png"))
# writeLines(gt::as_rtf(gt_tbl_trials), here::here("docs", "figures", "tbl-trials.rtf"))
